/**
 * Connects to OpenAI's Realtime API using WebRTC.
 * Uses the ephemeral token generated by our proxy.
 */
export class SttRealtimeClient {
  constructor(apiKey, onTranscript) {
    this.apiKey = apiKey;
    this.onTranscript = onTranscript;
    this.pc = null;
    this.dc = null;
    this.localStream = null;
    this.isActive = false;
  }

  async start() {
    this.isActive = true;
    
    // 1. Get Ephemeral Token
    const res = await fetch('/api/proxy/realtime-token', {
      method: 'POST',
      headers: {
        'x-lct-byok-key': this.apiKey
      }
    });

    if (!res.ok) {
      throw new Error('Failed to get realtime token');
    }
    const { client_secret: { value: ephemeralKey } } = await res.json();

    // 2. Setup WebRTC
    this.pc = new RTCPeerConnection();

    // 3. Setup Audio Capture
    this.localStream = await navigator.mediaDevices.getUserMedia({
      audio: {
        echoCancellation: true,
        noiseSuppression: true,
        autoGainControl: true
      }
    });

    // Add audio track to peer connection
    this.localStream.getTracks().forEach(track => {
      this.pc.addTrack(track, this.localStream);
    });

    // 4. Setup Data Channel for events
    this.dc = this.pc.createDataChannel('oai-events');
    this.dc.addEventListener('message', this.handleMessage.bind(this));

    // 5. Connect to OpenAI
    const offer = await this.pc.createOffer();
    await this.pc.setLocalDescription(offer);

    const baseUrl = "https://api.openai.com/v1/realtime";
    const model = "gpt-4o-mini-realtime-preview-2024-12-17"; // The fast transcribe model
    const sdpResponse = await fetch(`${baseUrl}?model=${model}`, {
      method: "POST",
      body: offer.sdp,
      headers: {
        Authorization: `Bearer ${ephemeralKey}`,
        "Content-Type": "application/sdp"
      },
    });

    if (!sdpResponse.ok) {
      throw new Error(`WebRTC connection failed: ${await sdpResponse.text()}`);
    }

    const answerSdp = await sdpResponse.text();
    await this.pc.setRemoteDescription({
      type: "answer",
      sdp: answerSdp,
    });
    
    // WebRTC connection is now establishing
  }

  handleMessage(e) {
    if (!this.isActive) return;
    try {
      const msg = JSON.parse(e.data);
      // We only care about transcription events
      // OpenAI emits 'conversation.item.input_audio_transcription.completed' when it finalizes a transcript
      if (msg.type === 'conversation.item.input_audio_transcription.completed') {
        const text = msg.transcript;
        if (text && text.trim()) {
          // Wrap it in our segment format (no strict speaker diarization from the realtime API yet, handled async later)
          const segment = {
            speaker: 'SPEAKER_00',
            text: text.trim(),
            start: performance.now() / 1000, // Approximate
            end: performance.now() / 1000,
            words: []
          };
          this.onTranscript([segment]);
        }
      }
    } catch (err) {
      console.warn("Error parsing realtime message:", err);
    }
  }

  stop() {
    this.isActive = false;
    
    if (this.localStream) {
      this.localStream.getTracks().forEach(t => t.stop());
      this.localStream = null;
    }
    if (this.dc) {
      this.dc.close();
      this.dc = null;
    }
    if (this.pc) {
      this.pc.close();
      this.pc = null;
    }
  }
}
